[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "formula-math"
version = "14.0.1"
description = "Math formulas as Python functions"
readme = "README.md"
authors = [{ name="Samarth Chugh" }]


